### ISSUE TITLE
Incorrect answer to math puzzle

### ISSUE THREAD

**Issue by andrewgordstewart** [norswap/norswap.github.io#3]
https://github.com/norswap/norswap.github.io/blob/321ada1527c4fd9ace249e28b8a219527565aaf0/blockchain-how/index.html#L215-L222

With the implicit assumption that the hashes we compute are uniformly distributed, the answer would be 4, more or less.

There are 1/4 * 2^256 valid hashes, and 2^256 total hashes. We want to draw one of them. So, n = 1, x = 2^256, y = 2^254. Applying the formula from math.stackexchange yields 1 * (2^256+1) / (2^254 + 1) ~ 2^256 / 2^254 = 4.

For some added intuition, note that for large decks that have lots of jacks (relative to the number of jacks we want to draw), drawing with or without replacement are practically equivalent. (It's not that hard to quantify this -- drawing without replacement is the same as drawing with replacement + marking drawn cards + ignoring marked cards, and when y >> n, you practically never draw a marked card.) Drawing with replacement, the expected number of draws to find n jacks is n/(probability of drawing a jack), which is n / (y / x) = n * x / y.

**Comment by norswap** [comment]
It seems like you're right! I can't recall how I got to those other figures.
Thanks for the report!

Fixed in 9abfc529c0c83fe0d78fab63e67cff2dd718effa
